<footer id="footer">

	<div class="footer-menu">
		<div class="container">
			<br>
			<ul class="list-inline social-icons">
				<li><a href="https://www.facebook.com/TeamPlaybr" title="Facebook TeamPlay"><img src="<?php assets('img/facebook.png'); ?>"></a></li>
				<li><a href="https://twitter.com/teamplay" target="_blank" title="Twitter TeamPlay"><img src="<?php assets('img/twitter.png'); ?>"></a></li>
				<li><a href="https://twitter.com/teamplay" target="_blank" title="Twitter TeamPlay"><img src="<?php assets('img/youtube.png'); ?>"></a></li>
			</ul>
			<ul class="nav navbar-nav">
				<li><a href="">Regras</a></li>
				<li><a href="">Política de privacidade</a></li>
				<li><a href="">Fale conosco</a></li>
			</ul>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container text-center">
			<p>© 2018 Blog b2ilha - Todos os direitos reservados.</p>
		</div>
	</div>
</footer>