
<div class="container">
	
	<div class="row row-bottom-20">
		<!-- MAIN -->
		<div role="main" class="col-md-7">
			<?=get('message') ?>
			<h1 class="text-white">Sk campeã da ECS </h1>

			<div class="card mb-3">
			  	<img class="card-img-top" src="<?php assets('img/ecs.jpg'); ?>" height="300px">
			  	<div class="card-body">
				    <h5 class="card-title">Card title</h5>
				    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
				    <a href="/posts/id" class="btn btn-info">Ver mais >></a>
			  	</div>
			  	<div class="card-footer">
			  		<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
			  	</div>
			</div>

			<div class="card mb-3">
			  	<img class="card-img-top" src="<?php assets('img/ecs.jpg'); ?>" height="300px">
			  	<div class="card-body">
				    <h5 class="card-title">Card title</h5>
				    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
				    <a href="#" class="btn btn-info">Ver mais >></a>
			  	</div>
			  	<div class="card-footer">
			  		<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
			  	</div>
			</div>

		</div>

		<!-- ASIDE -->
		<aside role="complementary" class="col-md-5 row-bottom-20">
			
            <div class="card text-white">
			  	<div class="card-body" style="padding-bottom: 0">
			    	<form action="">
			    		<div class="input-group mb-3">
						  	<input type="text" class="form-control" placeholder="Buscar">
						  	<div class="input-group-append">
						    	<button class="btn btn-info" type="submit"><i class="fa fa-search"></i> Buscar</button>
						  	</div>
						</div>
			    	</form>
			  	</div>
			</div>
			
			<div class="card text-dark row-bottom-20">
				<div class="card-header">
					Ultimos posts
				</div>

			  	<div class="card-body" style="padding-bottom: 0">
			  		<div class="row row-top-20">
			  			<div class="col-md-3">
				  			<img src="<?php assets('img/epicenter.jpg'); ?>" style="width: 75px; height: 75px;" class="rounded">
				  		</div>
				  		<div class="col-md-8 text-left" style="padding-top: 8px">
				  			<h5 class="card-title">Card title asasaas asa</h5>
				  			<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
				  		</div>
				  	</div>
				  	<hr>
				  	<div class="row row-top-20">
			  			<div class="col-md-3">
				  			<img src="<?php assets('img/epicenter.jpg'); ?>" style="width: 75px; height: 75px;" class="rounded">
				  		</div>
				  		<div class="col-md-8 text-left" style="padding-top: 8px">
				  			<h5 class="card-title">Card title asasaas asa</h5>
				  			<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
				  		</div>
				  	</div>
				  	<hr>
				  	<div class="row row-top-20">
			  			<div class="col-md-3">
				  			<img src="<?php assets('img/epicenter.jpg'); ?>" style="width: 75px; height: 75px;" class="rounded">
				  		</div>
				  		<div class="col-md-8 text-left" style="padding-top: 8px">
				  			<h5 class="card-title">Card title asasaas asa</h5>
				  			<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
				  		</div>
				  	</div>
			  	</div>
			</div>

			<div class="card text-dark row-bottom-20">
				<div class="card-header">
					Posts mais curtidos
				</div>

			  	<div class="card-body" style="padding-bottom: 0">
			  		<div class="row row-top-20">
			  			<div class="col-md-3">
				  			<img src="<?php assets('img/epicenter.jpg'); ?>" style="width: 75px; height: 75px;" class="rounded">
				  		</div>
				  		<div class="col-md-8 text-left" style="padding-top: 8px">
				  			<h5 class="card-title">Card title asasaas asa</h5>
				  			<p class="card-text">
				  				<small class="text-muted">
				  					Curtidas 	<i class="far fa-thumbs-up"></i> 20 | 
				  					Comentarios <i class="far fa-comments"></i> 30 |
				  					Data		<i class="far fa-calendar"></i> 20/02/2018
				  				</small>
				  			</p>
				  		</div>
				  	</div>
				  	<hr>
				</div>
			</div>

        </aside>


	</div>	
	
	
	
</div>

<footer id="footer">

	<div class="footer-menu">
		<div class="container">
			<br>
			<ul class="list-inline social-icons">
				<li><a href="https://www.facebook.com/TeamPlaybr" title="Facebook TeamPlay"><img src="<?php assets('img/facebook.png'); ?>"></a></li>
				<li><a href="https://twitter.com/teamplay" target="_blank" title="Twitter TeamPlay"><img src="<?php assets('img/twitter.png'); ?>"></a></li>
				<li><a href="https://twitter.com/teamplay" target="_blank" title="Twitter TeamPlay"><img src="<?php assets('img/youtube.png'); ?>"></a></li>
			</ul>
			<ul class="nav navbar-nav">
				<li><a href="">Regras</a></li>
				<li><a href="">Política de privacidade</a></li>
				<li><a href="">Fale conosco</a></li>
			</ul>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container text-center">
			<p>© 2018 Blog b2ilha - Todos os direitos reservados.</p>
		</div>
	</div>
</footer>




