

<div class="container">

    <div class="row row-bottom-20">

        <div class="col-md-6 offset-md-3">
            
            <div class="card ">
                <div class="card-header text-center">
                    <h2><i class="fa fa-unlock"></i> Realize seu login</h2>
                </div>
                <div class="card-body">
                    <?=get('message')?>
                    <?=get('error')?>

            
                    <form method="post" action="/recovers/account">

                        <div class="form-group ">
                            <label class="col-form-label"><i class="fa fa-envelope"></i> E-mail</label>
                            <input type="text" class="form-control <?= $this->errors['email'][0] ? 'is-invalid' : '' ?>" name="email" placeholder="Entre com seu email" value="">
                            <?php if (isset($this->errors['email'][0])) :  ?>
                                <div class="invalid-feedback"><?= $this->errors['email'][0] ?></div>
                            <?php endif; ?>
                        </div>

                        <button type="submit" class="btn btn-primary "><i class="fas fa-check-circle"></i> Recuperar</button>
                       
                    </form>
                </div>
                <div class="card-footer text-muted text-center">
                     <small class="text-right" ><a href="/login">Login</a></small>
                </div>
            </div>
        
        </div>

    </div>

</div>