

<div class="container">

    <div class="row row-bottom-20">

        <div class="col-md-6 offset-md-3">
            
            <div class="card ">
                <div class="card-header text-center">
                    <h2><i class="fas fa-address-card"></i> Crie sua conta</h2>
                </div>
                <div class="card-body">
                    <?=get('message')?>
                    <?=get('error')?>
                    <form method="post" action="/registre/store">


                    	<div class="form-group ">
                            <label class="col-form-label"><i class="fas fa-user"></i> Nome</label>
                            <input type="text" class="form-control <?=$this->errors['name'][0] ? 'is-invalid' : '' ?>" name="name" placeholder="Seu nome" value="">
                            <?php if (isset($this->errors['name'][0])) :  ?>
                                <div class="invalid-feedback"><?=$this->errors['name'][0] ?></div>
                            <?php endif; ?>
                        </div>


                        <div class="form-group ">
                            <label class="col-form-label"><i class="fas fa-user"></i> Usuário</label>
                            <input type="text" class="form-control <?=$this->errors['user'][0] ? 'is-invalid' : '' ?>" name="user" placeholder="Seu nome de usuário" value="">
                            <?php if (isset($this->errors['user'][0])) :  ?>
                                <div class="invalid-feedback"><?=$this->errors['user'][0] ?></div>
                            <?php endif; ?>
                        </div>



                        <div class="form-group ">
                            <label class="col-form-label"><i class="fas fa-envelope"></i> Email</label>
                            <input type="text" class="form-control <?=$this->errors['email'][0] ? 'is-invalid' : '' ?>" name="email" placeholder="Enter email" value="">
                            <?php if (isset($this->errors['email'][0])) :  ?>
                                <div class="invalid-feedback"><?=$this->errors['email'][0] ?></div>
                            <?php endif; ?>
                        </div>



                        <div class="form-group">
                            <label for="exampleInputPassword1"><i class="fas fa-lock"></i> Senha</label>
                            <input type="password" class="form-control <?=$this->errors['password'][0] ? 'is-invalid' : '' ?>" name="password" placeholder="Sua senha">
                            <?php if (isset($this->errors['password'][0])) :  ?>
                                <div class="invalid-feedback"><?=$this->errors['password'][0] ?></div>
                            <?php endif; ?>
                        </div>
        


                        <div class="form-group">
                            <label for="exampleInputPassword1"><i class="fas fa-lock"></i> Confirme a senha</label>
                            <input type="password" class="form-control <?=$this->errors['conf'][0] ? 'is-invalid' : '' ?>" name="conf" placeholder="Repita a sua senha">
                            <?php if (isset($this->errors['conf'][0])) :  ?>
                                <div class="invalid-feedback"><?=$this->errors['conf'][0] ?></div>
                            <?php endif; ?>
                        </div>



                        <button type="submit" class="btn btn-primary "><i class="far fa-save"></i> Cadastrar</button>
                       
                        
                    </form>
                </div>
                <div class="card-footer text-muted text-center">
                     <small class="text-right" ><a href="/">Realizar login</a></small>
                </div>
            </div>
        
        </div>

    </div>

</div>